/**
 * @file wifi_html_pages.h
 * @brief Embedded HTML pages for WiFi HTTP server
 *
 * Extracted from wifi_transfer.c to reduce file size.
 * All strings are null-terminated C string literals.
 */

#pragma once

/* ==================== OTA Page ==================== */

static const char OTA_PAGE_HEAD[] =
    "<!DOCTYPE html><html lang='zh'><head>"
    "<meta charset='utf-8'>"
    "<meta name='viewport' content='width=device-width,initial-scale=1'>"
    "<title>PPG Monitor - OTA</title>"
    "<style>"
    "*{margin:0;padding:0;box-sizing:border-box}"
    "body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;"
    "background:linear-gradient(135deg,#667eea 0%,#764ba2 100%);min-height:100vh;"
    "display:flex;align-items:center;justify-content:center;padding:20px}"
    ".card{background:#fff;border-radius:16px;box-shadow:0 20px 60px rgba(0,0,0,0.3);"
    "padding:40px;max-width:460px;width:100%}"
    "h1{font-size:24px;color:#333;margin-bottom:8px;text-align:center}"
    ".subtitle{color:#666;text-align:center;margin-bottom:24px;font-size:14px}"
    ".info{background:#f8f9fa;border-radius:8px;padding:12px 16px;margin-bottom:24px;"
    "font-size:13px;color:#555}"
    ".info span{color:#667eea;font-weight:600}"
    ".drop-zone{border:2px dashed #ccc;border-radius:12px;padding:40px 20px;"
    "text-align:center;cursor:pointer;transition:all .3s;margin-bottom:16px}"
    ".drop-zone:hover,.drop-zone.active{border-color:#667eea;background:#f0f2ff}"
    ".drop-zone p{color:#888;font-size:14px;margin-top:8px}"
    ".drop-zone .icon{font-size:48px}"
    ".file-info{display:none;background:#e8f5e9;border-radius:8px;padding:12px;"
    "margin-bottom:16px;font-size:13px;color:#2e7d32;word-break:break-all}"
    ".progress-container{display:none;margin-bottom:16px}"
    ".progress-bar{width:100%;height:24px;background:#e0e0e0;border-radius:12px;"
    "overflow:hidden;position:relative}"
    ".progress-fill{height:100%;background:linear-gradient(90deg,#667eea,#764ba2);"
    "width:0;transition:width .3s;border-radius:12px}"
    ".progress-text{position:absolute;top:0;left:0;right:0;text-align:center;"
    "line-height:24px;font-size:12px;font-weight:600;color:#333}"
    ".btn{width:100%;padding:14px;border:none;border-radius:8px;font-size:16px;"
    "font-weight:600;cursor:pointer;transition:all .3s}"
    ".btn-primary{background:linear-gradient(135deg,#667eea,#764ba2);color:#fff}"
    ".btn-primary:hover{transform:translateY(-2px);box-shadow:0 4px 15px rgba(102,126,234,0.4)}"
    ".btn-primary:disabled{opacity:.5;cursor:not-allowed;transform:none;box-shadow:none}"
    ".status{margin-top:16px;padding:12px;border-radius:8px;font-size:14px;"
    "text-align:center;display:none}"
    ".status.success{display:block;background:#e8f5e9;color:#2e7d32}"
    ".status.error{display:block;background:#ffebee;color:#c62828}"
    ".status.info{display:block;background:#e3f2fd;color:#1565c0}"
    ".reboot-info{display:none;margin-top:16px;text-align:center}"
    ".reboot-info .countdown{font-size:36px;font-weight:700;color:#667eea}"
    ".reboot-info p{color:#666;font-size:13px;margin-top:4px}"
    "input[type=file]{display:none}"
    "</style></head><body>"
    "<div class='card'>"
    "<h1>PPG Monitor</h1>"
    "<p class='subtitle'>Firmware Upgrade (OTA)</p>"
    "<div class='info'>"
    "Current: <span id='ver'>";

static const char OTA_PAGE_MID[] =
    "</span><br>"
    "Build: <span id='build'>";

static const char OTA_PAGE_MID2[] =
    "</span></div>"
    "<div class='drop-zone' id='dropZone' onclick='document.getElementById(\"fileInput\").click()'>"
    "<div class='icon'>&#128230;</div>"
    "<p>Drag .bin firmware here<br>or click to select file</p>"
    "</div>"
    "<div class='file-info' id='fileInfo'></div>"
    "<div class='progress-container' id='progressContainer'>"
    "<div class='progress-bar'>"
    "<div class='progress-fill' id='progressFill'></div>"
    "<div class='progress-text' id='progressText'>0%%</div>"
    "</div></div>"
    "<button class='btn btn-primary' id='uploadBtn' disabled onclick='startUpload()'>"
    "Start Upgrade</button>"
    "<div class='status' id='status'></div>"
    "<div class='reboot-info' id='rebootInfo'>"
    "<div class='countdown' id='countdown'>5</div>"
    "<p>seconds until page refresh</p>"
    "</div></div>"
    "<input type='file' id='fileInput' accept='.bin' onchange='onFileSelect(this)'>"
    "<script>"
    "var selectedFile=null;"
    "var dropZone=document.getElementById('dropZone');"
    "dropZone.addEventListener('dragover',function(e){e.preventDefault();this.classList.add('active')});"
    "dropZone.addEventListener('dragleave',function(){this.classList.remove('active')});"
    "dropZone.addEventListener('drop',function(e){"
    "e.preventDefault();this.classList.remove('active');"
    "if(e.dataTransfer.files.length)handleFile(e.dataTransfer.files[0])});"
    "function onFileSelect(input){if(input.files.length)handleFile(input.files[0])}"
    "function handleFile(file){"
    "if(!file.name.endsWith('.bin')){showStatus('Please select a .bin firmware file','error');return}"
    "selectedFile=file;"
    "document.getElementById('fileInfo').style.display='block';"
    "document.getElementById('fileInfo').innerHTML='&#128196; '+file.name+' ('+formatSize(file.size)+')';"
    "document.getElementById('uploadBtn').disabled=false;"
    "showStatus('File selected, click Start Upgrade','info')}"
    "function formatSize(bytes){"
    "if(bytes<1024)return bytes+'B';"
    "if(bytes<1048576)return (bytes/1024).toFixed(1)+'KB';"
    "return (bytes/1048576).toFixed(2)+'MB'}"
    "function startUpload(){"
    "if(!selectedFile)return;"
    "document.getElementById('uploadBtn').disabled=true;"
    "document.getElementById('progressContainer').style.display='block';"
    "showStatus('Uploading...','info');"
    "var xhr=new XMLHttpRequest();"
    "xhr.open('POST','/api/ota',true);"
    "xhr.upload.onprogress=function(e){"
    "if(e.lengthComputable){"
    "var pct=Math.round(e.loaded/e.total*100);"
    "document.getElementById('progressFill').style.width=pct+'%%';"
    "document.getElementById('progressText').textContent=pct+'%%'}};"
    "xhr.onload=function(){"
    "if(xhr.status===200){"
    "showStatus('Upgrade success! Device restarting...','success');"
    "document.getElementById('progressFill').style.width='100%%';"
    "document.getElementById('progressText').textContent='100%%';"
    "startCountdown()}else{"
    "showStatus('Upgrade failed: '+xhr.responseText,'error');"
    "document.getElementById('uploadBtn').disabled=false}};"
    "xhr.onerror=function(){"
    "showStatus('Network error, check connection','error');"
    "document.getElementById('uploadBtn').disabled=false};"
    "xhr.send(selectedFile)}"
    "function showStatus(msg,type){"
    "var el=document.getElementById('status');"
    "el.className='status '+type;el.textContent=msg}"
    "function startCountdown(){"
    "document.getElementById('rebootInfo').style.display='block';"
    "var sec=5;"
    "var timer=setInterval(function(){"
    "sec--;document.getElementById('countdown').textContent=sec;"
    "if(sec<=0){clearInterval(timer);location.reload()}},1000)}"
    "</script></body></html>";

/* ==================== Web Manager Page ==================== */

static const char WEB_MANAGER_PAGE[] =
    "<!DOCTYPE html><html><head><meta charset='UTF-8'>"
    "<meta name='viewport' content='width=device-width,initial-scale=1'>"
    "<title>PPG Monitor Manager</title>"
    "<style>"
    "*{margin:0;padding:0;box-sizing:border-box}"
    "body{font-family:-apple-system,sans-serif;background:#f5f5f5;color:#333}"
    ".header{background:#1976d2;color:#fff;padding:16px;text-align:center}"
    ".tabs{display:flex;background:#fff;border-bottom:1px solid #ddd}"
    ".tab{flex:1;padding:12px;text-align:center;cursor:pointer;border-bottom:2px solid transparent}"
    ".tab.active{border-bottom-color:#1976d2;color:#1976d2;font-weight:bold}"
    ".content{padding:16px;max-width:800px;margin:0 auto}"
    ".card{background:#fff;border-radius:8px;padding:16px;margin-bottom:16px;box-shadow:0 1px 3px rgba(0,0,0,0.1)}"
    ".card h3{margin-bottom:12px;color:#1976d2}"
    ".info-row{display:flex;justify-content:space-between;padding:8px 0;border-bottom:1px solid #eee}"
    ".progress-bar{height:20px;background:#e0e0e0;border-radius:10px;overflow:hidden;margin:8px 0}"
    ".progress-fill{height:100%;background:#4caf50;transition:width 0.3s}"
    ".progress-fill.warning{background:#ff9800}"
    ".progress-fill.danger{background:#f44336}"
    "table{width:100%;border-collapse:collapse}"
    "th,td{padding:8px;text-align:left;border-bottom:1px solid #eee}"
    "th{background:#f5f5f5;font-weight:bold}"
    ".btn{padding:6px 12px;border:none;border-radius:4px;cursor:pointer;font-size:12px}"
    ".btn-danger{background:#f44336;color:#fff}"
    ".btn-download{background:#1976d2;color:#fff}"
    ".hidden{display:none}"
    ".refresh-btn{position:fixed;bottom:20px;right:20px;width:50px;height:50px;border-radius:50%;background:#1976d2;color:#fff;border:none;font-size:20px;cursor:pointer;box-shadow:0 2px 5px rgba(0,0,0,0.3)}"
    "</style></head><body>"
    "<div class='header'><h1>PPG Monitor</h1><p>Web Manager</p></div>"
    "<div class='tabs'>"
    "<div class='tab active' onclick='showTab(0)'>System</div>"
    "<div class='tab' onclick='showTab(1)'>Storage</div>"
    "<div class='tab' onclick='showTab(2)'>Tasks</div>"
    "<div class='tab' onclick='showTab(3)'>Memory</div>"
    "</div>"
    "<div class='content'>"
    "<div id='tab0'></div><div id='tab1' class='hidden'></div>"
    "<div id='tab2' class='hidden'></div><div id='tab3' class='hidden'></div>"
    "</div>"
    "<button class='refresh-btn' onclick='refresh()'>↻</button>"
    "<script>"
    "let currentTab=0;"
    "function showTab(n){"
    "  document.querySelectorAll('.tab').forEach((t,i)=>t.classList.toggle('active',i===n));"
    "  document.querySelectorAll('[id^=tab]').forEach((t,i)=>t.classList.toggle('hidden',i!==n));"
    "  currentTab=n;refresh();"
    "}"
    "async function fetchJson(url){try{const r=await fetch(url);return await r.json()}catch(e){return null}}"
    "function progressBar(pct){"
    "  const cls=pct>80?'danger':pct>60?'warning':'';"
    "  return `<div class='progress-bar'><div class='progress-fill ${cls}' style='width:${pct}%%'></div></div>`;"
    "}"
    "async function refresh(){"
    "  if(currentTab===0){"
    "    const d=await fetchJson('/api/system');"
    "    if(!d)return;"
    "    document.getElementById('tab0').innerHTML=`"
    "      <div class='card'><h3>System Info</h3>"
    "      <div class='info-row'><span>Firmware</span><span>${d.firmware_version}</span></div>"
    "      <div class='info-row'><span>Build</span><span>${d.build_time}</span></div>"
    "      <div class='info-row'><span>Uptime</span><span>${Math.floor(d.uptime_seconds/3600)}h ${Math.floor(d.uptime_seconds%3600/60)}m</span></div>"
    "      <div class='info-row'><span>Chip</span><span>${d.chip_model}</span></div>"
    "      <div class='info-row'><span>CPU</span><span>${d.cpu_freq_mhz} MHz</span></div>"
    "      </div>`;"
    "  }else if(currentTab===1){"
    "    const d=await fetchJson('/api/storage');"
    "    if(!d)return;"
    "    let html=`<div class='card'><h3>TF Card</h3>"
    "      <div class='info-row'><span>Total</span><span>${d.sd_card.total_mb} MB</span></div>"
    "      <div class='info-row'><span>Used</span><span>${d.sd_card.used_mb} MB (${d.sd_card.used_percent}%%)</span></div>"
    "      <div class='info-row'><span>Free</span><span>${d.sd_card.free_mb} MB</span></div>"
    "      ${progressBar(d.sd_card.used_percent)}</div>`;"
    "    html+=`<div class='card'><h3>Directories</h3><table><tr><th>Name</th><th>Size</th><th>Files</th></tr>`;"
    "    for(const[name,info]of Object.entries(d.directories)){"
    "      html+=`<tr><td>${name}</td><td>${info.size_mb.toFixed(1)} MB</td><td>${info.file_count}</td></tr>`;"
    "    }"
    "    html+=`</table></div><div id='fileList'></div>`;"
    "    document.getElementById('tab1').innerHTML=html;"
    "    loadFiles();"
    "  }else if(currentTab===2){"
    "    const d=await fetchJson('/api/tasks');"
    "    if(!d)return;"
    "    let html=`<div class='card'><h3>FreeRTOS Tasks</h3><table>"
    "      <tr><th>Name</th><th>Priority</th><th>Stack Free</th><th>CPU %%</th></tr>`;"
    "    d.tasks.forEach(t=>{"
    "      const state=['Running','Ready','Blocked','Suspended','Deleted'][t.state]||'Unknown';"
    "      html+=`<tr><td>${t.name}</td><td>${t.priority}</td><td>${t.stack_free} B</td><td>${t.cpu_percent.toFixed(1)}%%</td></tr>`;"
    "    });"
    "    html+=`</table></div>`;"
    "    document.getElementById('tab2').innerHTML=html;"
    "  }else if(currentTab===3){"
    "    const d=await fetchJson('/api/memory');"
    "    if(!d)return;"
    "    document.getElementById('tab3').innerHTML=`"
    "      <div class='card'><h3>Heap Memory</h3>"
    "      <div class='info-row'><span>Total</span><span>${(d.heap.total/1024).toFixed(1)} KB</span></div>"
    "      <div class='info-row'><span>Used</span><span>${(d.heap.used/1024).toFixed(1)} KB (${d.heap.used_percent.toFixed(1)}%%)</span></div>"
    "      <div class='info-row'><span>Free</span><span>${(d.heap.free/1024).toFixed(1)} KB</span></div>"
    "      <div class='info-row'><span>Min Free Ever</span><span>${(d.heap.min_free_ever/1024).toFixed(1)} KB</span></div>"
    "      <div class='info-row'><span>Largest Block</span><span>${(d.heap.largest_block/1024).toFixed(1)} KB</span></div>"
    "      ${progressBar(d.heap.used_percent)}</div>`;"
    "  }"
    "}"
    "async function loadFiles(){"
    "  const d=await fetchJson('/api/files');"
    "  if(!d||!d.files)return;"
    "  let html=`<div class='card'><h3>Files</h3><table>"
    "    <tr><th>Name</th><th>Size</th><th>Action</th></tr>`;"
    "  d.files.forEach(f=>{"
    "    const size=f.size>1048576?(f.size/1048576).toFixed(1)+' MB':(f.size/1024).toFixed(1)+' KB';"
    "    html+=`<tr><td>${f.name}</td><td>${size}</td>"
    "      <td><button class='btn btn-download' onclick=\"window.open('/api/download?file=${f.name}')\">Download</button> "
    "      <button class='btn btn-danger' onclick=\"deleteFile('${f.name}')\">Delete</button></td></tr>`;"
    "  });"
    "  html+=`</table></div>`;"
    "  document.getElementById('fileList').innerHTML=html;"
    "}"
    "async function deleteFile(name){"
    "  if(!confirm('Delete '+name+'?'))return;"
    "  try{"
    "    const r=await fetch('/api/files/delete?path=/sdcard/'+name,{method:'POST'});"
    "    const d=await r.json();"
    "    if(d.status==='ok'){alert('Deleted');loadFiles();refresh();}"
    "    else alert('Delete failed');"
    "  }catch(e){alert('Error: '+e);}"
    "}"
    "refresh();setInterval(refresh,5000);loadFiles();"
    "</script></body></html>";
